/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:c813512d-8318-42dc-bb58-607499edfeed",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_u15sTFluv",
    "aws_user_pools_web_client_id": "1hcivfk7pvo35qj28o7glj1opq",
    "oauth": {}
}; 


export default awsmobile;
